### ISSUE TITLE
census data: year is a number so is shown as 1,999

### ISSUE THREAD

**Issue by arkarkark** [looker/census_looker#7]
this url 
https://census.looker.com/embed/explore/name_game/names_step_2?qid=ltYOFot9ujvWvbZsbfFxr5

![image](https://cloud.githubusercontent.com/assets/877895/17222772/c3220246-54ae-11e6-9e6a-13b869245449.png)

**Comment by dwmintz** [comment]
This is actually an issue inside Looker:

https://github.com/looker/helltool/issues/19656
